# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ferma.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ferma(object):
    def setupUi(self, ferma):
        ferma.setObjectName("ferma")
        ferma.resize(750, 478)
        ferma.setMinimumSize(QtCore.QSize(750, 478))
        ferma.setMaximumSize(QtCore.QSize(750, 478))
        ferma.setStyleSheet("background: #323450;")
        self.centralwidget = QtWidgets.QWidget(ferma)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 460, 750, 20))
        self.frame.setStyleSheet("background-color: rgb(212, 80, 54);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.consolLable = QtWidgets.QLabel(self.frame)
        self.consolLable.setGeometry(QtCore.QRect(9, 0, 341, 20))
        self.consolLable.setStyleSheet("border: 0;\n"
"color: rgb(52, 52, 52);")
        self.consolLable.setObjectName("consolLable")
        ferma.setCentralWidget(self.centralwidget)

        self.retranslateUi(ferma)
        QtCore.QMetaObject.connectSlotsByName(ferma)

    def retranslateUi(self, ferma):
        _translate = QtCore.QCoreApplication.translate
        ferma.setWindowTitle(_translate("ferma", "Ferma"))
        self.consolLable.setText(_translate("ferma", "TextLabel"))
