# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(740, 450)
        main.setMinimumSize(QtCore.QSize(740, 450))
        main.setMaximumSize(QtCore.QSize(740, 450))
        main.setStyleSheet("background: #323450;")
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.rsa = QtWidgets.QPushButton(self.centralwidget)
        self.rsa.setGeometry(QtCore.QRect(20, 30, 81, 23))
        self.rsa.setStyleSheet("background-color: rgb(149, 149, 149);")
        self.rsa.setObjectName("rsa")
        self.ferma = QtWidgets.QPushButton(self.centralwidget)
        self.ferma.setGeometry(QtCore.QRect(120, 30, 81, 23))
        self.ferma.setStyleSheet("background-color: rgb(149, 149, 149);")
        self.ferma.setObjectName("ferma")
        main.setCentralWidget(self.centralwidget)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Сryptography"))
        self.rsa.setText(_translate("main", "RSA"))
        self.ferma.setText(_translate("main", "Метод Ферма"))
